# Generated by Django 4.1.7 on 2023-03-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.AddField(
            model_name='about',
            name='picture',
            field=models.ImageField(null=True, upload_to='profile', verbose_name='picture'),
        ),
    ]
