# Generated by Django 4.1.7 on 2023-03-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_callback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backround', models.ImageField(upload_to='projects/background', verbose_name='')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('decription', models.TextField(verbose_name='description')),
                ('quote', models.CharField(blank=True, max_length=150, verbose_name='quote')),
                ('author', models.CharField(max_length=50, verbose_name='author')),
                ('picture1', models.ImageField(upload_to='projects/photo', verbose_name='picture1')),
                ('picture2', models.ImageField(upload_to='projects/photo', verbose_name='picture2')),
                ('cover', models.ImageField(upload_to='projects/cover', verbose_name='cover')),
                ('url', models.CharField(max_length=100, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
