# Generated by Django 4.1.7 on 2023-03-22 01:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_decription_projects_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('created', models.DateTimeField(verbose_name='created')),
            ],
            options={
                'verbose_name': 'BotUsers',
                'verbose_name_plural': 'BotUsers',
            },
        ),
        migrations.AddField(
            model_name='callback',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='backround',
            field=models.ImageField(upload_to='projects/background', verbose_name='background'),
        ),
    ]
