# Generated by Django 4.1.7 on 2023-03-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_botusers_callback_created_alter_projects_backround'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsDecription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
            ],
            options={
                'verbose_name': 'ProjectsDecription',
                'verbose_name_plural': 'ProjectsDecriptions',
            },
        ),
        migrations.AlterField(
            model_name='botusers',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='url',
            field=models.CharField(blank=True, max_length=100, verbose_name='url'),
        ),
    ]
