# Generated by Django 4.1.7 on 2023-03-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_projectsdecription_alter_botusers_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.ManyToManyField(to='main.projects', verbose_name='row')),
            ],
            options={
                'verbose_name': 'ProjectRow',
                'verbose_name_plural': 'ProjectRows',
            },
        ),
    ]
