# Generated by Django 4.1.7 on 2023-04-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_projectrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
    ]
